apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: notification-api-scaler
  namespace: notification
spec:
  scaleTargetRef:
    name: notification-api
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"
