global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "notification-api"
    static_configs:
      - targets: ["notification-api:8080"]

  - job_name: "notification-consumer"
    static_configs:
      - targets: ["notification-consumer:9090"]

  - job_name: "notification-scheduler"
    static_configs:
      - targets: ["notification-scheduler:9091"]

  - job_name: "notification-dbwriter"
    static_configs:
      - targets: ["notification-dbwriter:9092"]
