global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "notification-api"
    static_configs:
      - targets: ["notification-api:8080"]

  - job_name: "notification-consumer"
    dns_sd_configs:
      - names: ["notification-consumer"]
        type: A
        port: 9090

  - job_name: "notification-scheduler"
    dns_sd_configs:
      - names: ["notification-scheduler"]
        type: A
        port: 9091

  - job_name: "notification-dbwriter"
    dns_sd_configs:
      - names: ["notification-dbwriter"]
        type: A
        port: 9092
